# GET http://localhost:8080/api/v1/auth/signin
# Content-Type: application/json

# {
#     "title": "New data",
#     "body": "This is a new data"
# }

# GET http://localhost:8081/auth/signin
# Content-Type: application/json

# {
#     "title": "New data",
#     "body": "This is a new data"
# }

# GET http://localhost:8081/auth/signup
# Content-Type: application/json

# {
#     "title": "New data",
#     "body": "This is a new data"
# }

# POST  http://b2b.local:8080/api/v1/auth/signup/user?login=YURI&password=hello&email=xxx@xxx.com
# POST  http://localhost:8080/api/v1/auth/signup/user?login=YURI&password=hello&email=xxx@xxx.com
# GET http://localhost:8080/api/v1/auth/signup/user?login=qwdwq&email=xxx@xxx.com

# GET http://localhost:8080/api/v1/auth/signup/email/xxx@xxx.com
# GET http://localhost:8080/api/v1/auth/signup/login/yuri


# GET http://b2b.local:8080/api/v1/auth/signup/email/xxx@xxx.com
GET http://127.0.0.1:8080/api/v1/auth/signup/email/xxx@xxx.com