# GET http://localhost:8080/api/v1/auth/signin
# Content-Type: application/json

# {
#     "title": "New data",
#     "body": "This is a new data"
# }

# GET http://localhost:8081/auth/signin
# Content-Type: application/json

# {
#     "title": "New data",
#     "body": "This is a new data"
# }

# GET http://localhost:8081/auth/signup
# Content-Type: application/json

# {
#     "title": "New data",
#     "body": "This is a new data"
# }

# POST  http://b2b.local:8080/api/v1/auth/signup/user?login=YURI&password=hello&email=xxx@xxx.com
# POST  http://localhost:8080/api/v1/auth/signup/user?login=YURI1&password=hello&email=xx1x@xxx.com
# GET http://localhost:8080/api/v1/auth/signup/user?login=qwdwq&email=xxx@xxx.com

# GET http://localhost:8080/api/v1/auth/signup/email/xxx@xxx.com
# GET http://localhost:8080/api/v1/auth/signup/login/yuri


# GET http://b2b.local:8080/api/v1/auth/signup/email/xxx@xxx.com
# GET http://127.0.0.1:8080/api/v1/auth/signup/email/xxx@xxx.com

# signin
# GET http://localhost:8080/api/v1/auth/signin
# POST http://localhost:8080/api/v1/auth/signin/yuri
# POST http://localhost:8080/api/v1/auth/signin/yuri@gmail.com
# POST http://localhost:8080/api/v1/auth/signin/yuri/password

POST http://localhost:8080/api/v1/auth/signin/yuri@gmail.com/sdWE343sx!

###

# регистрация нового пользователя и авторизация
POST http://localhost:8080/api/v1/auth/signup/user?login=xxx&password=hello&email=xxx@xxx.com
# POST http://localhost:8080/api/v1/auth/signin/xxx@xxx.com/hello

###

POST http://localhost:8080/api/v1/auth/signin/yuri@gmail.com/sdWE343sx! HTTP/1.1
Content-Type: application/json
Authorization: sdfR@RF@
Username: yuri
Password: sdWE343sx!

###

POST http://localhost:8080/api/v1/auth/signup
Username: yuri
Email: yuri@gmail.com
Password: sdWE343sx!

###

POST http://localhost:8080/api/v1/auth/signin
Content-Type: application/json
Username: yuri
Password: sdWE343sx!

###